#!/usr/bin/ruby
require "pathname"
ENV["GEM_HOME"] = nil if ENV["GEM_HOME"] and !Pathname.new(ENV["GEM_HOME"]).exist?
ENV["GEM_PATH"] = nil if ENV["GEM_PATH"] and !Pathname.new(ENV["GEM_PATH"]).exist?

require 'rubygems'
require 'libisi'
init_libisi
optparse
initialize_rails

print "Loading default working items.\n"

View.load_from_yaml("#{RAILS_ROOT}/config/default_working_items/views.yaml", :primary_key => "name")

