debian/tmp/etc/alois/boot.rb
debian/tmp/etc/alois/database.yml
debian/tmp/etc/alois/environment.rb
debian/tmp/etc/alois/routes.rb
debian/tmp/etc/alois/environments/production.rb
debian/tmp/etc/default/alois-environment.rb
debian/tmp/etc/default/alois-environment-config.rb

debian/tmp/usr/share/alois/www/doc
debian/tmp/usr/share/alois/www/db
debian/tmp/usr/share/alois/www/app
debian/tmp/usr/share/alois/www/java
debian/tmp/usr/share/alois/www/public
debian/tmp/usr/share/alois/www/script
debian/tmp/usr/share/alois/www/config/default_working_items
debian/tmp/usr/share/alois/www/config/initializers
debian/tmp/usr/share/alois/www/config/locales
debian/tmp/usr/share/alois/www/components
debian/tmp/usr/share/alois/www/lib

debian/tmp/usr/share/alois/www/vendor
debian/tmp/usr/share/alois/www/Rakefile
debian/tmp/usr/share/alois/www/README



