debian/tmp/usr/share/prisma
#debian/tmp/var/lib/prisma/archive/README

debian/tmp/usr/bin/prisma
debian/tmp/usr/bin/prisma-compress-archives
debian/tmp/usr/bin/prisma-delete-old-logs
debian/tmp/usr/bin/prisma-sendlog
debian/tmp/usr/bin/prisma-test
debian/tmp/usr/bin/prisma-cleanup-raws
debian/tmp/usr/bin/prisma-munin-pumpyflows
debian/tmp/usr/bin/prisma-compress-archives
debian/tmp/usr/bin/prisma-delete-old-logs
debian/tmp/usr/bin/prisma-mysqlpipe
debian/tmp/usr/bin/prisma-import-file

#debian/tmp/usr/bin/prisma-munin-aloisdb
#debian/tmp/usr/bin/prisma-munin-sinkdb
#debian/tmp/usr/bin/prisma-munin-sinkflows
debian/tmp/usr/bin/prisma-munin-pumpydb
debian/tmp/usr/bin/prisma-munin-prismadb
debian/tmp/usr/bin/prisma-munin-iptablesflows
debian/tmp/usr/bin/prisma-munin-pumpyflows

debian/tmp/usr/lib/ruby/1.8/prisma.rb
debian/tmp/usr/lib/ruby/1.8/prisma

debian/tmp/etc/prisma/environment.rb
debian/tmp/etc/prisma/environment_production.rb
debian/tmp/etc/prisma/prisma_database.yml
debian/tmp/etc/prisma/pumpy_database.yml

debian/tmp/etc/prisma/environment.rb
debian/tmp/etc/prisma/environment_production.rb
debian/tmp/etc/prisma/prisma_database.yml
debian/tmp/etc/prisma/pumpy_database.yml
